### ISSUE TITLE
performance data integration milestones w/dates

### ISSUE THREAD

**Issue by anyaelena** [NREL/Wattile#149]
notes:

1. refactor
2. sandbox deployment
3. prod skyspark updates
4. one model train/deploy

considerations: full time dashboard developer ramping up in Sep

**Comment by stephen-frank** [comment]
I think this can be closed? All models are trained and ready to be deployed, but deployment is going to wait on a Wattile 0.2 release.

**Comment by haneslinger** [comment]
i think your right
