### ISSUE TITLE
for charlie - dealing with `configs["qs"]`

### ISSUE THREAD

**Issue by JanghyunJK** [NREL/Wattile#156]
- currently, `configs["qs"]` takes a list of float numbers for defining quantiles
- `charlie` currently only takes one float number
- potential paths
  - make wattile to take `configs["qs"]` as list and do multiple trainings as Liang did ?
  - make wattile to just train single model based on one float number (equal to 0.5) ?

**Comment by stephen-frank** [comment]
Per group decision 11/22/2024, Charlie will be deprecated and removed
