### ISSUE TITLE
for charlie - adding all performance metrics

### ISSUE THREAD

**Issue by JanghyunJK** [NREL/Wattile#157]
- currently, only couple metrics are calculated
- while we originally set up these below for `alfa` and `bravo`

RMSE | CV(RMSE) | NMBE | GOF | QS | ACE | IS
-- | -- | -- | -- | -- | -- | --

- also, this should also cover logging metrics in `Training_history.csv` file
- and maybe, showing similar display output as `alfa`/`bravo` would look better

**Comment by stephen-frank** [comment]
Per group decision 11/22/2024, Charlie will be deprecated and removed
