### ISSUE TITLE
Docker should not run as root

### ISSUE THREAD

**Issue by stephen-frank** [NREL/Wattile#240]
Implement a non-root (`skyspark`?) user and group for the docker container. See: https://www.geeksforgeeks.org/docker-user-instruction/

**Comment by stephen-frank** [comment]
For the Wattile generic Docker image (if it still exists), the solution used in [nrelWattileExt](https://github.com/NREL/nrelWattileExt/pull/49) should work, and the UID/GID matching isn't even necessarily needed. If not, this can be closed.

**Comment by haneslinger** [comment]
can we close in favor of https://github.com/NREL/nrelWattileExt/issues/44?

**Comment by stephen-frank** [comment]
Yes
