### ISSUE TITLE
input and parameter tensors are not at the same device

### ISSUE THREAD

**Issue by JanghyunJK** [NREL/Wattile#243]
- this came up while testing on HPC
- somewhat related to "scenario 3" in this issue: https://github.com/NREL/Wattile/issues/235
- I thought it worked before without this change, but now it's not 😵

- error:
```
RuntimeError: Input and parameter tensors are not at the same device, found input tensor at cuda:0 and parameter tensor at cpu
```

- error happens when:
  - model is trained (`run_training`) on GPU (HPC)
  - and the same model is validated (`run_validation`) on GPU (HPC)

- possible solution:
  - I think this line in `run_training` should also be included in `run_validataion`  https://github.com/NREL/Wattile/blob/227fc3438a346960bc77c3d9605e5ccb41dab35b/wattile/models/alfa_model.py#L349-L350

- double check from @buechler314 would be appreciated!!

**Comment by haneslinger** [comment]
Closed with #244
