### ISSUE TITLE
FTLB Models for Deployment Testing

### ISSUE THREAD

**Issue by stephen-frank** [NREL/Wattile#250]
Train models on HPC for the FTLB to be used in deployment testing. There should be models for each of the following meters:

1. FTLB Main Electricity
2. FTLB Chilled Water (CHW) Consumption
3. FTLB Hot Water (HW) Consumption

I will email the data set link to @JanghyunJK. 

**Important!** Ensure the following settings when training these models:

- Time interval should be 15 minutes. Note: targets are at a more granular resolution, but I think the data processing pipeline is set up to handle this now, correct?
- Set intervals to **left-closed** (`bin_closed` = "left" and optionally `bin_label` = "left")
- Use architecture "alfa"
- Train quantiles [0.1, 0.2, ..., 0.9]
- Ensure the resulting models can be executed on CPU. I think this just means I will need to have a build of Wattile with #244 merged?

Time proxy variables (sin/cos, binary indicators, etc.) are at your discretion based on what has worked well. Or just use all of them if you like. :)

This issue is for progress tracking. Let me know if there are questions.

**Comment by JanghyunJK** [comment]
just uploaded new data to HPC
![image](https://user-images.githubusercontent.com/26775789/207427774-69846f43-aa38-4fec-b827-e86d5a1bf8b1.png)

**Comment by JanghyunJK** [comment]
@stephen-frank trained model results for different combinations of `bin_closed` and `bin_label` are uploaded in the shared folder. I'll send an email shortly with specific link to the folder location.

**Comment by stephen-frank** [comment]
I think there are some issues when `bin_closed = left`. I will gather info and post a bug.

**Comment by stephen-frank** [comment]
Received FTLB models from Janghyun. Closing as complete!
