### ISSUE TITLE
Create more input/output test cases for data pre-processing

### ISSUE THREAD

**Issue by stephen-frank** [NREL/Wattile#260]
Create more tests for data pre-processing that include combinations of the following:

- `bin_label` left/right
- `bin_closed` left/right
- With rolling statistics on or off

The goal is to test the various data processing cases that could arise.

**Comment by JanghyunJK** [comment]
tying this issue (https://github.com/NREL/Wattile/issues/258) to this issue as my intention was similar.

**Comment by stephen-frank** [comment]
Implemented in #263
