### ISSUE TITLE
Poetry fails to install torch 1.13.1 (Windows)

### ISSUE THREAD

**Issue by stephen-frank** [NREL/Wattile#275]
I'm trying to get my environment set up properly for Wattile, but `poetry install` and `poetry update` fail to find torch 1.13.1:

```
  ▒ Installing torch (1.13.1): Failed

  RuntimeError

  Unable to find installation candidates for torch (1.13.1)
```

![image](https://user-images.githubusercontent.com/1534082/230686897-2cffd40b-15df-417a-9b27-7685b497ba24.png)

Unsure how to check what versions are available.

**Comment by stephen-frank** [comment]
Evidently this is a Python 3.11+ issue. (Python 3.8 is on a legacy build cycle, so I just installed 3.11. Uninstalling 3.11 and installing 3.10 fixed this issue.)

**Comment by haneslinger** [comment]
It seems likely to need to update your pip version. 

run `poetry run pip -V` to get poetry's pip version. 
run `poetry run pip install torch==test` to see the available torch versions. 
run `python -m pip install --upgrade pip`to upgrade pip.

**Comment by stephen-frank** [comment]
Also upgraded pip. This is resolved; closing...
