### ISSUE TITLE
Empty columns cause size mismatch error in calculating rolling mean

### ISSUE THREAD

**Issue by stephen-frank** [NREL/Wattile#283]
This is similar to #281, but this time the culprit is completely empty data columns rather than NA values in a data column. The behavior is similar, though:

```
axon::EvalErr: Func failed: pyEval(PySession py,Str stmt); args: (PyMgrSession,Str)
  sys::IOErr: Python failed: operands could not be broadcast together with shapes (121,77) (121,79) 
Traceback (most recent call last):
  File "/usr/src/app/hxpy/hxpy.py", line 67, in run
    self._exec(instr, local_vars)
  File "/usr/src/app/hxpy/hxpy.py", line 95, in _exec
    return exec(code, local_vars, local_vars)
  File "<string>", line 1, in <module>
  File "/wattile/wattile/buildings_processing.py", line 512, in prep_for_rnn
    data = _preprocess_data(configs, data)
  File "/wattile/wattile/buildings_processing.py", line 486, in _preprocess_data
    data = roll_data(data, configs)
  File "/wattile/wattile/buildings_processing.py", line 571, in roll_data
    means.loc[:, :] = sums.values / counts.values
ValueError: operands could not be broadcast together with shapes (121,77) (121,79) 
 [proj_dash::wattilePythonModelPredict:148]
```

The error still traces back to these lines: https://github.com/NREL/Wattile/blob/hpc_run/wattile/buildings_processing.py#L567-L571

I will send input data for this error via email as well.

**Comment by haneslinger** [comment]
I swapped out the sum/count for just using the mean, which  seemed to work 🤷‍♀️ we should check with Janghyun first tho

**Comment by JanghyunJK** [comment]
"It will mostly work but not always" was the case before. I would have to track my notes to find where that `mean` was failing (or not doing what it should supposed to be).

**Comment by haneslinger** [comment]
do you know the case it wouldn't work? I'd be happy to test it.

**Comment by haneslinger** [comment]
https://github.com/NREL/Wattile/pull/285
