### ISSUE TITLE
Add support for MLflow logging

### ISSUE THREAD

**Issue by smithcommajoseph** [NREL/Wattile#325]
Originally, I pitched the use of mlflow's autologging feature for Wattile models. Unfortunately, autologging is not available for torch models 

"Unlike other deep learning flavors, MLflow does not have an autologging integration with PyTorch because native PyTorch requires writing custom training loops" - [MLFlow](https://mlflow.org/docs/latest/deep-learning/pytorch/guide/index.html)

Looking at the code, I believe adding MLFlow logging will require modifying each model class as I don't see enough shared functionality where training is concerned to add this in the base model class. Not a deal breaker, but sharing here so as not to surprise anyone.

**Comment by stephen-frank** [comment]
#326
